config/routes.rb
Ftcalendar::Application.routes.draw do

  devise_for :admins, path_names: {
      sign_up: 'super-secret-signup'
  }

  authenticated :admin do
    root :to => 'home#index'
  end
  root :to => "home#index"

  resources :events
  match 'all_events' => 'events#all_events'
  match '/home/events' => 'home#events'
  
  resources :home
  match '/about' => 'info#about'
  match '/contact' => 'info#contact'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :description, :ends_at, :max_volunteers, :signup_url, :starts_at, :title, :organization, :contact, :street, :city, :state, :zip, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode

  searchable do
    text :description
    text :title
    text :organization
    text :signup_url
    text :contact
    text :city
    text :state
    text :street
     :max_volunteers
  end

def address
  [street, city, state, zip].compact.join(', ')
end


  validates_presence_of :description, :ends_at,
                        :max_volunteers, :signup_url,
                        :starts_at, :title, :organization,
                        :contact, :street, :city, :state, :zip


  validates_date :starts_at, :on_or_before => lambda { :ends_at }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_admin!, :except => [:show, :all_events, :index]

  def new
    @event = Event.new
  end

  def edit
    id = params[:id]
    @event = Event.find(id)
    @event.starts_at= @event.starts_at.strftime("%m/%d/%Y %l:%M %p")
    @event.ends_at= @event.ends_at.strftime("%m/%d/%Y %l:%M %p")
  end

  def show
    id = params[:id]
    @event = Event.find(id)
  end

  def create
    event_params = params[:event]
    begin
      event_params['starts_at'] = DateTime.strptime(event_params['starts_at'], "%m/%d/%Y %l:%M %p")
      event_params['ends_at'] = DateTime.strptime(event_params['ends_at'], "%m/%d/%Y %l:%M %p")
    rescue ArgumentError
      flash[:alert] = "Please enter valid dates."
      @event = Event.new(event_params)
      render 'new'
      return
    end

    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "#{@event.title} was successfully created."
      redirect_to @event
    else
      flash[:alert] = "Please correct these errors: " + @event.errors.full_messages.join(". ")
      render 'new'
    end
  end

  def update
    @event = Event.find params[:id]

    event_params = params[:event]
    begin
      event_params['starts_at'] = DateTime.strptime(event_params['starts_at'], "%m/%d/%Y %l:%M %p")
      event_params['ends_at'] = DateTime.strptime(event_params['ends_at'], "%m/%d/%Y %l:%M %p")
    rescue ArgumentError
      flash[:alert] = "Please enter valid dates."
      render 'edit'
      return
    end

    @event.update_attributes!(params[:event])
    flash[:notice] = "#{@event.title} was successfully updated."
    redirect_to @event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event '#{@event.title}' deleted."
    redirect_to '/'
  end

  def index
    if admin_signed_in?
      @events = Event.find(:all, :order => :starts_at)
    else
      @events = Event.near(request.remote_ip, 30, :order => :starts_at)
    end
    if params[:query]
      @search = Event.search do
        fulltext params[:query]
        #fields(:description, :title)
      end
      if admin_signed_in?
        @events = @search.results
        @events.sort! {|a,b| a.starts_at <=> b.starts_at}
      else
        @events = @search.results & @events
        @events.sort! {|a,b| a.starts_at <=> b.starts_at}
      end
    end
  end

  def all_events
    if admin_signed_in?
      @events = Event.all
    else
      @events = Event.near(request.remote_ip, 30)
    end
    @events.each do |event|
      event.starts_at = event.starts_at.to_i
      event.ends_at = event.ends_at.to_i
    end
    render json: @events
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end

  def contact
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/edit.html.haml
%h1 Edit Event

= form_for @event, :method => :put, :validate => true do |e|
  .fieldset
    .form-group
      = e.label :title, 'Title'
      %p
      = e.text_field :title
    .form-group
      = e.label :organization, 'Organization'
      %p
      = e.text_field :organization
    .form-group
      = e.label :contact, 'Contact Email'
      %p
      = e.text_field :contact
    .form-group
      = e.label :starts_at, 'Start Date'
      = e.text_field :starts_at
    .form-group
      = e.label :ends_at, 'End Date'
      = e.text_field :ends_at
    .form-group
      = e.label :description, 'Description'
      = '(Mention any specific requirements (i.e., age))' 
      %p
      = e.text_area :description, :rows => 5
    .form-group
      = e.label :street, 'Street'
      = e.text_field :street
      = e.label :city, 'City'
      = e.text_field :city
    .form-group
      = e.label :state, 'State'
      = e.text_field :state
      = e.label :zip, 'Zip Code'
      = e.text_field :zip
    .form-group
      = e.label :signup_url, 'Sign Up Link'
      %p
      = e.text_field :signup_url
    .form-group
      = e.label :max_volunteers, 'Max Volunteers'
      %p
      = e.number_field :max_volunteers

    = submit_tag 'Update Event Info'
= button_to 'Cancel', root_path


:javascript
  $(document).ready(function() {
    $('#event_starts_at').datetimepicker(
    {
      addSliderAccess: true,
      sliderAccessArgs: { touchonly: false },
      timeFormat: "h:mm TT"
     });

    $('#event_ends_at').datetimepicker(
    {
      addSliderAccess: true,
      sliderAccessArgs: { touchonly: false },
      timeFormat: "h:mm TT"
     });
  });

app/views/events/index.html.haml
%table.table.table-striped.table-condensed.table-hover.table-bordered.table-responsive#eventTable
  %thead
    %tr
      %th.title Title
      %th Organization Name
      %th Start Date
      %th Address
      %th Max Volunteers
      %th Event Link
      - if admin_signed_in?
        %th Edit Event
 
  %tbody
    - @events.each do |event|
      %tr
        %td= link_to event.title, event_path(event)
        %td= event.organization
        %td= event.starts_at.strftime("%m/%d/%Y %l:%M %p")
        %td= event.address
        %td= event.max_volunteers
        %td= link_to 'View Event', event_path(event)
        - if admin_signed_in?
          %td= link_to 'Edit Event', edit_event_path(event)
      
        
    - if @events.length == 0
      %h4 No events found. Try less specific search terms.
= button_to 'Back to Calendar', root_path

app/views/events/new.html.haml
%h1 Create New Event

= form_for @event, :validate => true do |e|
  .fieldset
    .form-group
      = e.label :title, 'Title'
      %p
      = e.text_field :title
    .form-group
      = e.label :organization, 'Organization'
      %p
      = e.text_field :organization
    .form-group
      = e.label :contact, 'Contact Email'
      %p
      = e.text_field :contact
    .form-group
      = e.label :starts_at, 'Start Date'
      = e.text_field :starts_at
    .form-group
      = e.label :ends_at, 'End Date'
      = e.text_field :ends_at

    .form-group
      = e.label :description, 'Description'
      = '(Mention any specific requirements (i.e., age))' 
      %p
      = e.text_area :description, :rows => 5

    .form-group
      = e.label :street, 'Street'
      = e.text_field :street
      = e.label :city, 'City'
      = e.text_field :city
    .form-group
      = e.label :state, 'State'
      = e.text_field :state
      = e.label :zip, 'Zip Code'
      = e.text_field :zip
    .form-group
      = e.label :signup_url, 'Sign Up Link'
      %p
      = e.text_field :signup_url
    .form-group
      = e.label :max_volunteers, 'Max Volunteers'
      %p
      = e.number_field :max_volunteers

    = submit_tag 'Save Changes'
= button_to 'Cancel', root_path

:javascript
  $(document).ready(function() {


    $('#event_starts_at').datetimepicker(
    {
      addSliderAccess: true,
      sliderAccessArgs: { touchonly: false },
      timeFormat: "h:mm TT",
      defaultValue: "select a date/time"
     });

    $('#event_ends_at').datetimepicker(
    {
      addSliderAccess: true,
      sliderAccessArgs: { touchonly: false },
      timeFormat: "h:mm TT",
      defaultValue: "select a date/time"
     });
  });

app/views/events/show.html.haml
%h2 #{@event.title}

%ul.customList#details
  %li
    %b Starts At:
    = @event.starts_at.strftime("%m/%d/%Y %l:%M %p")
  %li
    %b Ends At:
    = @event.ends_at.strftime("%m/%d/%Y %l:%M %p")
  %li
    %b Address:
    = @event.address
  %li
    %b Max Volunteers:
    = @event.max_volunteers

%h3 Description:
%p#description= @event.description
%br
%br
%form{:action => url_with_protocol(@event.signup_url)}
  %input{:type => "submit", :value => "Sign Up to Volunteer"}
= button_to 'Back to Calendar', root_path

- if admin_signed_in?
  %h3 Admin Actions:
  = button_to 'Edit', edit_event_path(@event), :method => :get
  = button_to 'Delete', event_path(@event), :method => :delete, :confirm => 'Are you sure?'

app/views/home/index.html.haml
.entire-page
#calendar

:javascript
  $(document).ready(function() {
      $.getJSON('/all_events', function(jsonEvents) {
          var events = [];
          for (var i = 0; i < jsonEvents.length; i++) {
              var currEvent = convertToEvent(jsonEvents[i]);
              events.push(currEvent);
          }
          $('#calendar').fullCalendar({
              header: {
                  left: 'prev,next today',
                  center: 'title',
                  right: 'month,basicWeek,basicDay'
              },
              defaultView: 'basicWeek',
              editable: false,
              events: events,
              eventMouseover: function(event, jsEvent, view) {
                var moveLeft = -20;
                var moveDown = 20;
                $('#popup' + event['id']).show();
                $(this).mousemove(function(e) {
                  $("#popup" + event['id']).css('top', e.pageY + moveDown).css('left', e.pageX + moveLeft);
                  });
              },
              eventMouseout: function(event, jsEvent, view) {
                $('#popup' + event['id']).hide();
              }
          });
          var delta = $(calendar).parent().parent().width() - $(calendar).width();
          $(calendar).parent().css('margin-left',delta/2);
          $(calendar).parent().width($(calendar).parent().width() + delta/2);
      });
  });


- @events.each do |event|
  %div{:id => "popup" + event.id.to_s, :class => "popups", :style => "z-index: 10;"}
    %h3.noMarginPadding= event.title
    %ul.customList
      %li
        %b Starts At:
        = event.starts_at.strftime("%m/%d/%Y %l:%M %p")
      %li
        %b Ends At:
        = event.ends_at.strftime("%m/%d/%Y %l:%M %p")
      %li
        %b Address:
        = event.address
      %li
        %b Max Volunteers:
        = event.max_volunteers
    %h4 Description:

    %p= event.description

app/views/info/about.html.haml
.about-page
  %div#infoText
    %h1 Our Story
    %p
      %i Forward Tutoring is a 501(c)(3) nonprofit organization that empowers students to pay     forward online tutoring with community service.
    %br
    %p Powerless, we watched our siblings and classmates struggle helplessly with homework, not to mention exams. They couldn't afford the tutoring. So C's displaced B's. D's displaced C's. And F's displaced not only marks on their transcript but also their belief that they could succeed in school--that they were smart. As we saw their discouragement grow, we realized that there must be a better way for students to get help in school. A way that’s convenient, reliable, AND free. So we asked: instead of paying back the tutoring with money, why not pay it forward with volunteer service?
    %br
    %p
      In the summer of 2011, before our last year of high school, we teamed up--all seven of us--and we said enough is enough.
      Models for accessing quality, one-on-one online tutoring, finding service opportunities, and recruiting volunteers must change.
      And so Forward Tutoring was born, in idea and in execution.
    %br
    %p

      That year, at the Texas Academy of Mathematics and Science and the University of North Texas, we found developers, mentors, and supporters.
      Since then, we’ve grown our team over threefold, created a system we’re really proud of, and even won some awards in the process.
      We’ve learned to serve and served to learn. We’re originally from Dallas, Texas, but we’ve realized that we can’t stop here.
    %br
    %p
      Our goal is to establish college chapters nationwide, engaging communities everywhere on the ground level.
      No organization should be left without volunteers, and no student should struggle helplessly in school again.
    %br

    %p
      %b
        %i - The Forward Tutoring Team
    %br
    %p
      %i
        Forward Tutoring Calendar was developed by: Ken Szubzda, Arham Jain, Chris Talley, Danial Asif, Malika Rajvanshy, and Manisha Eerabathini

app/views/info/contact.html.haml
.contact-page
  %div#infoText
    %h1 Contact Us
    %p
      Our main site is found here at
      %a{href: "http://www.forwardtutoring.org"} www.forwardtutoring.org
    %br
    %p
      %u Questions about volunteer hours or a volunteer opportunity?
      %br
      %a{href: "mailto:submithours@forwardtutoring.org"} submithours@forwardtutoring.org
      can answer your questions.
    %br
    %p
      %u To submit hours:
      %br
      Send
      %a{href: "http://www.forwardtutoring.org/sites/default/files/FT%20Volunteer%20Guidelines.pdf"} this pdf
      with your username to
      %a{href: "mailto:submithours@forwardtutoring.org"} submithours@forwardtutoring.org
    %br
    %p
      %u
        Questions about Forward Tutoring and signing up to become a student?
    %p
      By Phone: 1(888) 670-2276
    %p
      By Email:
      %a{href: "mailto:contact@forwardtutoring.org"} contact@forwardtutoring.org
    %p
      By Mail:
    %i Texas:
    PO Box 117495,Carrollton, Texas 75011-7495
    %br
    %i  Connecticut:
    206 Elm St. #207051, New Haven, CT 06520-7051
    %br
    %br
    %p
      Contact us through Twitter and like us on
      %a{href: "http://www.facebook.com/forwardtutoring"} Facebook!
      %br
      twitter: @forwardtutoring
      %br
      Google+: forwardtutoring

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.container{'data-dropdown' => 'dropdown'}
  .top-bar
    .navbar-header
      .ft-icon
        = link_to(image_tag("logo.png"), root_path)
      
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        
        %li.active
          %a{href: root_path} Calendar
        %li
          %a{href: events_path} Events
        %li
          %a{href: about_path} About
        %li
          %a{href: contact_path} Contact 
        
      %ul.nav.navbar-nav.navbar-right
        %li.search-bar
          = form_tag events_path, :class => "navbar-form", :role => "search", :method => :get, :validate => true do
            = text_field_tag :query,nil, placeholder: 'Enter your search here'
            = submit_tag 'Search', :name => nil
        - if admin_signed_in?
          %li
            = link_to 'Logout', destroy_admin_session_path, :method=>'delete'
        - else
          %li
            = link_to 'Login', new_admin_session_path
        - if admin_signed_in?
          %li
            = link_to 'Edit Account', edit_admin_registration_path
          %li
            = link_to "Create Event", new_event_path
    / /.nav-collapse
    
  

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Forward Tutoring Calendar"
    %meta{content: content_for?(:description) ? yield(:description) : "Forward Tutoring Calendar", name: "description"}/
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css"
    = javascript_include_tag "application", "rails.validations"
    -#= javascript_include_tag params[:controller]
    = csrf_meta_tags
    = yield(:head)
  %body{class: "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
    / ! end of #container
    .ftcontent
      #main{role: "main"}
        = yield
      %footer